import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
import { image } from "../../image/logo_base64";

pdfMake.vfs = pdfFonts.pdfMake.vfs;
pdfMake.fonts = {
  THSarabun: {
    normal: "THSarabunNew.ttf",
    bold: "THSarabunNew Bold.ttf",
    italics: "THSarabunNew Italic.ttf",
    bolditalics: "THSarabunNew Bold Italic.ttf",
  },
};

export default function PdfRemain() {
  let win = window.open("", "_blank");
  const date = new Date();
  let docDefinition = {
    footer: function (currentPage, pageCount) {
      return [
        {
          canvas: [
            {
              type: "line",
              x1: 40,
              y1: -5,
              x2: 555,
              y2: -5,
              lineWidth: 1,
            },
          ],
        },
        {
          columns: [
            {
              text: "เจ้าหน้าที่ ชื่อตัวอย่าง นามสกุลตัวอย่าง ผ่ายตรวจสอบรายได้",
              alignment: "left",
              fontSize: 9,
              margin: [40, 0, 0, 0],
            },
            {
              text: "วันอังคารที่ 29 ธันวาคม 2563 15.30น.",
              alignment: "right",
              fontSize: 9,
              margin: [0, 0, 40, 0],
            },
          ],
        },
      ];
    },
    content: [
      {
        columns: [
          { image: `data:image/png;base64,${image}`, width: 60 },
          //   { text: `test`, width: 60 },
          {
            width: "auto",
            stack: [
              {
                text: "ฝ่ายตรวจสอบรายได้",
                fontSize: 20,
                bold: true,
                margin: [20, 5, 0, 0],
              },
              {
                canvas: [
                  {
                    type: "line",
                    x1: 20,
                    y1: 2,
                    x2: 455,
                    y2: 2,
                    lineWidth: 1,
                  },
                ],
              },
              {
                text: "กองทางหลวงพิเศษระหว่างเมือง กรมทางหลวง",
                fontSize: 14,
                margin: [20, 0, 0, 0],
              },
            ],
          },
        ],
      },

      {
        text: "รายงานคงค้าง",
        alignment: "center",
        fontSize: 20,
        bold: true,
        margin: [0, 5, 0, 0],
      },
      { text: `${date}`, alignment: "center", fontSize: 14 },
      {
        text: "หน่วยงานรับการตรวจสอบ 902 - ทับช้าง 1",
        fontSize: 14,
        margin: [0, 10, 0, 0],
      },
      {
        text: "เอกสาร ตรวจสอบความถูกต้องของการตรวจรายได้ประจำวัน",
        fontSize: 14,
      },
      {
        columns: [
          {
            headerRows: 1,
            style: "table",
            table: {
              widths: [150, 50, 30],
              body: [
                [
                  {
                    text: "สรุปรายละเอียดรายได้คงค้างรายเดือน",
                    border: [true, true, true, false],
                    colSpan: 3,
                    bold: true,
                    alignment: "left",
                  },
                  {},
                  {},
                ],
                [
                  {
                    text: "รายละเอียด ด่านทับช้าง 1",
                    border: [true, false, true, false],
                    alignment: "left",
                    margin: [0, -5, 0, 0],
                    colSpan: 3,
                  },
                  {},
                  {},
                ],
                [
                  {
                    text: "ตั้งแต่ วันที่ 1 ธันวาคม 2563 - 31 ธันวาคม 2563(รายเดือน)",
                    border: [true, false, true, false],
                    alignment: "left",
                    margin: [0, -5, 0, 0],
                    colSpan: 3,
                  },
                  {},
                  {},
                ],
                [
                  {
                    text: "จำนวนรถทั้งหมด",
                    border: [true, false, false, false],
                    alignment: "left",
                    margin: [0, -2, 0, 0],
                  },
                  {
                    text: "49,600",
                    border: [false, false, false, false],
                    margin: [0, -2, 0, 0],
                    alignment: "left",
                  },
                  {
                    text: "คัน",
                    border: [false, false, true, false],
                    margin: [0, -2, 0, 0],
                    alignment: "left",
                  },
                ],
                [
                  {
                    text: "เงินพึงได้ทั้งหมด",
                    border: [true, false, false, false],
                    alignment: "left",
                    margin: [0, -5, 0, 0],
                  },
                  {
                    text: "49,600,000",
                    border: [false, false, false, false],
                    margin: [0, -5, 0, 0],
                    alignment: "left",
                  },
                  {
                    text: "บาท",
                    border: [false, false, true, false],
                    margin: [0, -5, 0, 0],
                    alignment: "left",
                  },
                ],
                [
                  {
                    text: "เงินที่จัดเก็บได้ทั้งหมด",
                    border: [true, false, false, false],
                    alignment: "left",
                    margin: [0, -5, 0, 0],
                  },
                  {
                    text: "7,409,000",
                    border: [false, false, false, false],
                    margin: [0, -5, 0, 0],
                    alignment: "left",
                  },
                  {
                    text: "บาท",
                    border: [false, false, true, false],
                    margin: [0, -5, 0, 0],
                    alignment: "left",
                  },
                ],
                [
                  {
                    text: "คงค้างทั้งหมด",
                    border: [true, false, false, false],
                    alignment: "left",
                    margin: [0, -5, 0, 0],
                  },
                  {
                    text: "42,191,000",
                    border: [false, false, false, false],
                    margin: [0, -5, 0, 0],
                    alignment: "left",
                  },
                  {
                    text: "บาท",
                    border: [false, false, true, false],
                    margin: [0, -5, 0, 0],
                    alignment: "left",
                  },
                ],
                [
                  {
                    text: "ค่าปรับทั้งหมด",
                    border: [true, false, false, true],
                    alignment: "left",
                    margin: [0, -5, 0, 0],
                  },
                  {
                    text: "4,960,000",
                    border: [false, false, false, true],
                    margin: [0, -5, 0, 0],
                    alignment: "left",
                  },
                  {
                    text: "บาท",
                    border: [false, false, true, true],
                    margin: [0, -5, 0, 0],
                    alignment: "left",
                  },
                ],
              ],
            },
          },
          {
            style: "table",
            table: {
              widths: [40, 45, 50, 35, 35],
              body: [
                [
                  {
                    text: "ประเภทรถ",
                    rowSpan: 2,
                    border: [true, true, true, true],
                    margin: [0, 5, 0, 0],
                  },
                  { text: "จำนวนรถทั้งหมด", border: [true, true, true, false] },
                  {
                    text: "จำนวนรถที่ผิดพลาด",
                    border: [true, true, true, false],
                  },
                  { text: "รถยกเว้น", border: [true, true, true, false] },
                  { text: "รถที่คงค้าง", border: [true, true, true, false] },
                ],
                [
                  {},
                  {
                    text: "(คัน)",
                    border: [true, false, true, true],
                    margin: [0, -5, 0, 0],
                  },
                  {
                    text: "(คัน)",
                    border: [true, false, true, true],
                    margin: [0, -5, 0, 0],
                  },
                  {
                    text: "(คัน)",
                    border: [true, false, true, true],
                    margin: [0, -5, 0, 0],
                  },
                  {
                    text: "(คัน)",
                    border: [true, false, true, true],
                    margin: [0, -5, 0, 0],
                  },
                ],
                [
                  { text: "C1" },
                  { text: "15" },
                  { text: "5" },
                  { text: "4" },
                  { text: "3" },
                ],
                [
                  { text: "C2" },
                  { text: "20" },
                  { text: "9" },
                  { text: "0" },
                  { text: "1" },
                ],
                [
                  { text: "C3" },
                  { text: "15" },
                  { text: "5" },
                  { text: "4" },
                  { text: "3" },
                ],
                ["รวมทั้งหมด", "15", "5", "4", "3"],
              ],
            },
          },
        ],
        columnGap: 5,
      },
      {
        style: "table2",
        table: {
          widths: [50, 58, 58, 58, 58, 58, 58, "*"],
          headerRows: 2,
          body: [
            [
              { text: "ด่าน", rowSpan: 2, margin: [0, 5, 0, 0] },
              { text: "วันเดือนปีการเก็บ", rowSpan: 2, margin: [0, 5, 0, 0] },
              { text: "จำนวนรถทั้งหมด", border: [true, true, true, false] },
              { text: "เงินพึงได้ทั้งหมด", border: [true, true, true, false] },
              { text: "เงินที่จัดเก็บได้", border: [true, true, true, false] },
              { text: "จำนวนรถคงค้าง", border: [true, true, true, false] },
              { text: "จำนวนเงินคงค้าง", border: [true, true, true, false] },
              { text: "ค่าปรับทั้งหมด", border: [true, true, true, false] },
            ],
            [
              {},
              {},
              { text: "(คัน)", border: [true, false, true, true] },
              { text: "(บาท)", border: [true, false, true, true] },
              { text: "(บาท)", border: [true, false, true, true] },
              { text: "(คัน)", border: [true, false, true, true] },
              { text: "(บาท)", border: [true, false, true, true] },
              { text: "(บาท)", border: [true, false, true, true] },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "27/12/2020" },
              { text: "100" },
              { text: "100,000" },
              { text: "89,000" },
              { text: "50" },
              { text: "11,000" },
              { text: "10,000" },
            ],
          ],
        },
      },
    ],
    styles: {
      table: { marginTop: 10, alignment: "center", fontSize: 9 },
      table2: { marginTop: 10, alignment: "center", fontSize: 9 },
    },
    defaultStyle: { font: "THSarabun" },
  };
  pdfMake.createPdf(docDefinition).download("รายงานคงค้าง.pdf");
}
