import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
import { image } from "../../image/logo_base64";

pdfMake.vfs = pdfFonts.pdfMake.vfs;
pdfMake.fonts = {
  THSarabun: {
    normal: "THSarabunNew.ttf",
    bold: "THSarabunNew Bold.ttf",
    italics: "THSarabunNew Italic.ttf",
    bolditalics: "THSarabunNew Bold Italic.ttf",
  },
};

export default function PdfSumMonthly() {
  // console.log(report1);
  const date = new Date();
  let docDefinition = {
    footer: function () {
      return [
        {
          canvas: [
            {
              type: "line",
              x1: 40,
              y1: -5,
              x2: 555,
              y2: -5,
              lineWidth: 1,
            },
          ],
        },
        {
          columns: [
            {
              text: "เจ้าหน้าที่ ชื่อตัวอย่าง นามสกุลตัวอย่าง ผ่ายตรวจสอบรายได้",
              alignment: "left",
              fontSize: 9,
              margin: [40, 0, 0, 0],
            },
            {
              text: "วันอังคารที่ 29 ธันวาคม 2563 15.30น.",
              alignment: "right",
              fontSize: 9,
              margin: [0, 0, 40, 0],
            },
          ],
        },
      ];
    },
    content: [
      {
        columns: [
          { image: `data:image/png;base64,${image}`, width: 60 },
          //   { text: `test`, width: 60 },
          {
            width: "auto",
            stack: [
              {
                text: "ฝ่ายตรวจสอบรายได้",
                fontSize: 20,
                bold: true,
                margin: [20, 5, 0, 0],
              },
              {
                canvas: [
                  {
                    type: "line",
                    x1: 20,
                    y1: 2,
                    x2: 455,
                    y2: 2,
                    lineWidth: 1,
                  },
                ],
              },
              {
                text: "กองทางหลวงพิเศษระหว่างเมือง กรมทางหลวง",
                fontSize: 14,
                margin: [20, 0, 0, 0],
              },
            ],
          },
        ],
      },

      {
        text: "สรุปใบนำฝากประจำเดือน",
        alignment: "center",
        fontSize: 20,
        bold: true,
        margin: [0, 5, 0, 0],
      },
      { text: `${date}`, alignment: "center", fontSize: 14 },
      {
        text: "หน่วยงานรับการตรวจสอบ 902 - ทับช้าง 1",
        fontSize: 14,
        margin: [0, 10, 0, 0],
      },
      {
        text: "เอกสาร ตรวจสอบความถูกต้องของการตรวจรายได้ประจำวัน",
        fontSize: 14,
      },

      {
        margin: [13, 10, 0, 0],
        style: "table",
        table: {
          widths: [70, 45, 20, 70, 45, 20, 70, 45, 20],
          body: [
            [
              {
                text: "รายได้ด่านทับช้าง 1",
                border: [true, true, true, false],
                colSpan: 3,
                bold: true,
                alignment: "left",
                fontSize: 11,
              },
              {},
              {},
              {
                text: "ค่าปรับด่านทับช้าง 1",
                border: [true, true, true, false],
                colSpan: 3,
                bold: true,
                alignment: "left",
                fontSize: 11,
              },
              {},
              {},
              {
                text: "สรุปข้อมูล",
                border: [true, true, true, false],
                colSpan: 3,
                bold: true,
                alignment: "left",
                fontSize: 11,
              },
              {},
              {},
            ],
            [
              {
                text: "รายได้ที่พึงได้",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "1,000,000",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
              {
                text: "ค่าปรับที่เกิดขึ้น",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "300,000",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
              {
                text: "จำนวนรถทั้งหมด",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "132,246",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "คัน",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
            ],
            [
              {
                text: "รายได้ที่ได้รับ",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "500,000",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
              {
                text: "เรทค่าปรับ",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "300,000",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
              {
                text: "จำนวนรถ C1 ทั้งหมด",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "31,465",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "คัน",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
            ],
            [
              {
                text: "รวมทั้งสิ้น",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "500,000",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
              {
                text: "ค่าปรับที่ทำการชำระ",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "200,000",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
              {
                text: "จำนวนรถ C2 ทั้งหมด",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "31,496",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "คัน",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
            ],
            [
              {
                text: "คงค้าง",
                border: [true, false, false, true],
                alignment: "left",
                margin: [0, -5, 0, 5],
                rowSpan: 4,
              },
              {
                text: "500,000",
                border: [false, false, false, true],
                margin: [0, -5, 0, 5],
                rowSpan: 4,
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, true],
                margin: [0, -5, 0, 5],
                rowSpan: 4,
              },
              {
                text: "รวมทั้งสิ้น",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "200,000",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
              {
                text: "จำนวนรถ C3 ทั้งหมด",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "31,527",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "คัน",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
            ],
            [
              {},
              {},
              {},
              {
                text: "คงค้าง",
                border: [true, false, false, true],
                alignment: "left",
                margin: [0, -5, 0, 3],
                rowSpan: 3,
              },
              {
                text: "100,000",
                border: [false, false, false, true],
                margin: [0, -5, 0, 3],
                rowSpan: 3,
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, true],
                margin: [0, -5, 0, 3],
                rowSpan: 3,
              },
              {
                text: "จำนวนรถยกเว้นทั้งหมด",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "31,496",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "คัน",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
            ],
            [
              {},
              {},
              {},
              {},
              {},
              {},
              {
                text: "จำนวนรถคงค้างทั้งหมด",
                border: [true, false, false, false],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "31,558",
                border: [false, false, false, false],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "คัน",
                border: [false, false, true, false],
                margin: [0, -5, 0, 0],
              },
            ],
            [
              {},
              {},
              {},
              {},
              {},
              {},
              {
                text: "ค่าปรับทั้งหมด",
                border: [true, false, false, true],
                alignment: "left",
                margin: [0, -5, 0, 0],
              },
              {
                text: "4,960,000",
                border: [false, false, false, true],
                margin: [0, -5, 0, 0],
                alignment: "left",
              },
              {
                text: "บาท",
                border: [false, false, true, true],
                margin: [0, -5, 0, 0],
              },
            ],
          ],
        },
      },

      {
        style: "table2",
        table: {
          widths: [
            30,
            "auto",
            40,
            30,
            "auto",
            "auto",
            20,
            40,
            30,
            "auto",
            40,
            "auto",
          ],
          headerRows: 2,
          body: [
            [
              { text: "ด่าน", rowSpan: 2, margin: [0, 5, 0, 0] },
              { text: "transaction", rowSpan: 2, margin: [0, 5, 0, 0] },
              { text: "เข้าด่าน", colSpan: 2 },
              {},
              { text: "ประเภทรถ", rowSpan: 2, margin: [0, 5, 0, 0] },
              { text: "ค่าผ่านทาง", border: [true, true, true, false] },
              { text: "ค่าปรับ", border: [true, true, true, false] },
              { text: "จัดเก็บ", colSpan: 2 },
              {},
              { text: "ชำระแล้ว", border: [true, true, true, false] },
              { text: "ทะเบียน", rowSpan: 2, margin: [0, 5, 0, 0] },
              { text: "จังหวัด", rowSpan: 2, margin: [0, 5, 0, 0] },
            ],
            [
              {},
              {},
              { text: "วันที่" },
              { text: "เวลา" },
              {},
              {
                text: "(บาท)",
                border: [true, false, true, true],
              },
              {
                text: "(บาท)",
                border: [true, false, true, true],
              },
              { text: "วันที่" },
              { text: "เวลา" },
              {
                text: "(บาท)",
                border: [true, false, true, true],
              },
              {},
              {},
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ทับช้าง1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
            [
              { text: "ธัญบุรี1" },
              { text: "M202109010000000001" },
              { text: "27/12/2020" },
              { text: "13.24น." },
              { text: "C1" },
              { text: "30" },
              { text: "60" },
              { text: "29/12/2020" },
              { text: "14.14น." },
              { text: "90" },
              { text: "กข3210" },
              { text: "กรุงเทพมหานคร" },
            ],
          ],
        },
      },
    ],
    styles: {
      table: { marginTop: 20, alignment: "center", fontSize: 9 },
      table2: { marginTop: 10, alignment: "center", fontSize: 9 },
    },
    defaultStyle: { font: "THSarabunNew" },
  };
  pdfMake.createPdf(docDefinition).download("สรุปใบนำฝากประจำเดือน.pdf");
}
